### ISSUE TITLE
Option to add a label to the "All" option

### ISSUE THREAD

**Issue by cdcharlebois** [tieniber/GridSearch#10]
currently the "all" option is just blank--it would be great to have an option for what to put in for the caption
![image](https://user-images.githubusercontent.com/2905603/43156647-bbec68fa-8f48-11e8-8288-92930892b5b8.png)

**Comment by tieniber** [comment]
Done!
<img width="606" alt="screen shot 2018-07-24 at 5 19 14 pm" src="https://user-images.githubusercontent.com/3960619/43166838-b7676f4c-8f65-11e8-80c7-7b6653e8dae1.png">
