### ISSUE TITLE
Search field is cleared after opening entry, but filtering is still in place

### ISSUE THREAD

**Issue by Erwin-t-Hoen** [tieniber/GridSearch#2]
When using the widget with a simple grid and filtering on a string attribute, navigating to a new page with the button on the grid and returning to the grid will empty the search field but will keep the filtering on the grid.
For example The grid shows 2 records with attribute set to a or b.
I enter b in the search field.
Now the grid is filtered and shows only one record (b).
The next action is to press the new button on the grid and create a new record with the attribute set to c and pressing save. I'm now returned to the grid and see that the search field is emptied, but the list is still showing one record (b). Either keep the search field filled or reset the grid.

**Comment by tieniber** [comment]
In v2, I've updated the widget to properly keep its state when going back to a page.
