### ISSUE TITLE
Empty caption not displayed & configure placeholder text

### ISSUE THREAD

**Issue by rickyv3** [tieniber/GridSearch#22]
Hi Eric,

The empty caption is not displayed when using the drop down - dynamic widget (although it does work for the static drop down).

It would also be nice if I could configure the placeholder text for the multifield text input search, and selectively show/hide the label for the reset widget.

 Using Mx v.7.22.1

Thank you,
Ricky

**Comment by tieniber** [comment]
Hi Ricky, I fixed the empty caption issue in the latest commit. I'll look at the multifield placeholder and reset button soon.

**Comment by rickyv3** [comment]
Hi Eric,

The issue doesn't seem to be resolved for me. I used the package in the branch - dist folder. Is that correct?

**Comment by tieniber** [comment]
Can you share your widget’s configuration? Also, what browser are you using? My test project had 1 config where the placeholder text worked and 1 where it didn’t. In the latest commit, both work, so I need a new reproduction case.

**Comment by rickyv3** [comment]
Chrome v 71.0.3578.98

the same page includes the dynamic drop down (config below) plus the drop down - static, multifield and reset widgets.

![dynamicdropconfig](https://user-images.githubusercontent.com/13573078/52648371-071b6800-2eac-11e9-88bd-73736eba7017.png)
![dynamicdropconfig2](https://user-images.githubusercontent.com/13573078/52648372-071b6800-2eac-11e9-958d-0defcf59ce9c.png)

**Comment by tieniber** [comment]
Found it - the issue only occurred when multi-select was enabled. Fixed in the latest commit. Please review and let me know if it also works for you.

**Comment by rickyv3** [comment]
Yep, that did it. Thanks!


Best Regards,

Ricky Volz
kinetech <http://kinetechcloud.com> *| *tel: 210.254.4988
