### ISSUE TITLE
Dynamic dropdown cascade error

### ISSUE THREAD

**Issue by jacobdehorn** [tieniber/GridSearch#29]
![image](https://user-images.githubusercontent.com/30499911/53880480-5ff4a100-4011-11e9-825f-c62de2a20713.png)
I use mendix 7.23.1 

![image](https://user-images.githubusercontent.com/30499911/53880495-671baf00-4011-11e9-8180-c8b94ea9cde3.png)

**Comment by cdcharlebois** [comment]
Hi @jacobdehorn, can you please share the configuration of the other widget on the page?

**Comment by jacobdehorn** [comment]
@cdcharlebois  Thanks for you reply. I have a feeling that the Path to listen is the cause of the error. But when I leave it out it shows all the Subapplications.  I hope you can help me further. 

![image](https://user-images.githubusercontent.com/30499911/53942912-42304600-40bc-11e9-97ba-7a18e9bfd20c.png)

**Comment by cdcharlebois** [comment]
hm, your configuration seems right. @jacobdehorn, I will attempt to recreate the issue in 7.23.1. In the meantime, could you please share a small test project where this issue is occurring?

**Comment by cdcharlebois** [comment]
In the test project for this widget, when using cascading filters, in the higher-level filter (your _Application_ filter), the filter attribute is set to go **through** the lower-lever association. i.e. all Products in a SubApplication the belongs to the selected Application. Can you try configuring your Application filter with the following for Attribute (manual):
Product >> Application >> SubApplication
`Benchmarking.Product_Application/Benchmarking.Application/Benchmarking.SubApplication_Application/Benchmarking.SubApplication/Name` (assuming that this is a valid path in your domain model)

**Comment by jacobdehorn** [comment]
@cdcharlebois Thanks for your reply and your help, I tried your suggestion but this did not do anything else. In the zipfile you find a small test project I created and recreated the problem.  I hope find a sollution for me. 

[TestDynamicDD.zip](https://github.com/tieniber/GridSearch/files/2945305/TestDynamicDD.zip)

**Comment by cdcharlebois** [comment]
Hi @jacobdehorn, I was able to recreate and resolve the issue in the test project you sent. Thanks for that! Can you please try [this build](https://github.com/cdcharlebois/GridSearch/blob/master/test/widgets/GridSearch.mpk?raw=true) of the widget and let me know if it resolves the problem for you? If so we'll get this merged into the master line of this widget.

Thanks!
Conner

**Comment by jacobdehorn** [comment]
Hi Connor, thanks for the reply and your effort to help me. It works properly now, so that's great!!
Thank you!

Edit: One thing that is not working properly is that when you set "Multi-select" to Yes, and you select 2 or more applications, you only see the sub applications of the latest checked application, in stead of all the sub applications of the checked applications. 

Jacob

**Comment by cdcharlebois** [comment]
@tieniber can you please mark this issue as closed/resolved?
