### ISSUE TITLE
Ability to search n-deep

### ISSUE THREAD

**Issue by Mcpoowl** [tieniber/GridSearch#4]
Hi Eric,

Awesome widget, which would be even of greater use, if you could access entities n-deep.
For example:

My Connection is a part of a Customer ( a Customer can have multiple Connections ), that Customer has an Account Manager.

In my DataGrid which shows Connections, I want to be able to search on Account Manager.
The default Mendix search boxes allow this. In the widget I'm limited by 1-deep.

**Comment by tieniber** [comment]
Added in latest version!
