### ISSUE TITLE
datasource.setconstraints is not a function error on mendix 8.17.0

### ISSUE THREAD

**Issue by Snailpower** [tieniber/GridSearch#50]
While using any of the widgets to filter a datagrid that has a microflow as data source, clicking any of the filter buttons gives an error in the debugger.

The filter is then not applied to the datagrid.

I saw a lot of comments about this issue in the reviews on the mendix app store, any idea when this might be fixed for new mendix 8 versions?

Edit: some screenshots attached

In the application:
![image](https://user-images.githubusercontent.com/16387086/106013067-66d0a500-60bc-11eb-899d-9bc8ffb5933c.png)

![image](https://user-images.githubusercontent.com/16387086/106013264-92538f80-60bc-11eb-9588-d81535dd063a.png)

In the log:

![image](https://user-images.githubusercontent.com/16387086/106013115-718b3a00-60bc-11eb-8747-af950e80e188.png)

**Comment by tieniber** [comment]
99% sure this has been addressed in 3.2.1 or 3.2.2. Please re-open if it's still a problem.
