### ISSUE TITLE
Different language for "placeholder" value is not available. 

### ISSUE THREAD

**Issue by joeavelar** [tieniber/GridSearch#51]
Using Mendix modeler 8.6.9; we are not able to set or define a different value for the "placeholder". In our case we need the French language "Rechercher" to be defined for the "placeholder" instead of the default "Search". 

![image](https://user-images.githubusercontent.com/43994252/107657175-eaf56180-6c52-11eb-9bfd-277cd5c5beac.png)

Would it possible to allow a change that would enable setting the "placeholder" value somewhere within? 

![image](https://user-images.githubusercontent.com/43994252/107657601-4cb5cb80-6c53-11eb-907f-1c0e35718b44.png)

**Comment by cdcharlebois** [comment]
It looks like the default "Search" option is put there from the template. Should be able to set that from a widget property: https://github.com/tieniber/GridSearch/blob/89a06f6de6aa6f14a7ee8710a8bdd70103ef54f8/src/GridSearch/widget/template/GridSearch.html#L6

**Comment by cdcharlebois** [comment]
Actually, after @joeavelar's update via email this morning, it appears that this is already fixed in the latest version https://github.com/tieniber/GridSearch/blob/master/src/GridSearch/widget/GridSearch.js#L48, so I think we can close this issue

**Comment by joeavelar** [comment]
Thank you.
