### ISSUE TITLE
Anysearch widget error e.getAttribute is not a function TypeError: e.getAttribute is not a function mendix version 9.6.0

### ISSUE THREAD

**Issue by epalmen** [tieniber/GridSearch#58]
Using the Anysearch is great but suddenly i got the below error.
Am using a listview  which is filtert with support of the anysearch,

Have cleaned my userlib directory 
changed name of the listview but still getting the same error.

Please advise
regards Erik

e.getAttribute is not a function TypeError: e.getAttribute is not a function
    at Object.byNode (http://localhost:8080/mxclientsystem/mxui/mxui.js?637740543651682544:5:159175)
    at HTMLDivElement._connectOneGrid (http://localhost:8080/widgets/GridSearch/widget/Core.js?637740543651682544:89:30)

**Comment by basjonkerr** [comment]
I'm getting the same errors for all the search widgets in MX 9.6.6

**Comment by tieniber** [comment]
See #59
