### ISSUE TITLE
Grid Search is not working after upgrading to Mendix 9.6.3

### ISSUE THREAD

**Issue by LItal1234** [tieniber/GridSearch#59]
I am using the Grid Search widget quite a lot in my app. Unfortunately after upgrading to Mendix 9.6.3 it’s stop working. I upgraded to the latest Grid Search widget but it didn’t help. I am using the 'comparison' and 'dropdown' static/dynamic.
Error is “e.getAttribute is not a function TypeError: e.getAttribute is not a function at Object.byNode(http://localhost:8080/mxclientsystem/mxui/mxui.js?6375...) at HTMLDivElement._connectOneGrid (http://localhost:8080/widgets/GridSearch/widget/Core.js?6377...)”.

**Comment by basjonkerr** [comment]
I'm getting the same error in 9.6.6

**Comment by tieniber** [comment]
See here for the explanation and workaround:

https://forum.mendix.com/link/questions/112055
