### ISSUE TITLE
DEPRECATED: logger, use mx.logger instead -- will be removed in version: 11.0

### ISSUE THREAD

**Issue by basi01** [tieniber/GridSearch#62]
We have the Comparison widget on our page and when we open the app in browser 3 or more messages are logged to the Studio console:

    DEPRECATED: logger, use mx.logger instead -- will be removed in version: 11.0

the stack trace shows that the first call is from postCreate() in GridSearchMX.js

We use widget version 3.2.1 and Studio 9.6.5

**Comment by tieniber** [comment]
Addressed in 3.2.2, released today.
