### ISSUE TITLE
NaN to NaN Error

### ISSUE THREAD

**Issue by Loko75** [tieniber/GridSearch#63]
Hello,

i realy love and need this widget. I am using it since years but after the upgrade to MX9 and Atlas3 it's showing NaN to NaN instead of any numbers (for the pagining) and i am not able to change the pages anymore.
Currently I am using:
 - MX9.10.1
 - Atlas 3
 - GridSearch v3.2.1

I added an example app as attachment.

I hope you can get it fixed, the shitstorm of my users is massive :) 

![2021-12-30 17_17_34-Window](https://user-images.githubusercontent.com/99711330/154002475-0f0450e7-a8d5-4edf-95c6-831629e382f8.png)
[SendSafely_download_RB7R-B98E.zip](https://github.com/tieniber/GridSearch/files/8066264/SendSafely_download_RB7R-B98E.zip)
.

**Comment by tieniber** [comment]
Fixed in 3.2.2. Give it a try and be sure to review the note at the top of the documentation.

**Comment by Loko75** [comment]
That was a quick fix, thank you !
