### ISSUE TITLE
Have a requirement to search across multiple grids on a page

### ISSUE THREAD

**Issue by cdcharlebois** [tieniber/GridSearch#8]
instead of targeting just one grid node by name, can we have it target a set of grid nodes by classname? and apply the filters to all of them, simultaneously? To clarify, this would mean one set of filters, that get applied to a number of grids.

**Comment by tieniber** [comment]
Complete in latest commit. Use the "Grid Class" parameter instead of "Grid Name" to target multiple grids with the same class.

**Comment by ssuijkerbuijk** [comment]
Hi @tieniber , should this also work with multiple lists on 1 page? I'm using the "Dropdown - Dynamic"widget and want to filter on 2 lists on the same page. Using the grid class option here doesn't work. Only the first list is filtered, 

Edit: Looks like the widget has problems filtering lists that are not directly visible but made visible after loading the page with conditional visibility. Filtering on lists not directly visible after loading the page, doesn't work. Any workaround for this possible?

MX 7.18.1
